### ISSUE TITLE
No data for Greater Anglia

### ISSUE THREAD

**Issue by nworbneb** [morosanmihail/HA-LondonTfL#14]
Great integration!

It's working for central line with Stratford station, however it doesn't seem to pull Greater Anglia stations.  The sensor is generated and updating, but there are no attributes.

**Comment by morosanmihail** [comment]
Sadly, that's a limitation of the TfL API. It has information about stations, but no data on schedules (at least not realtime). 
There are very few non-TfL lines that have data. You've now discovered Greater Anglia is not one of them :(
