### ISSUE TITLE
Updating Sensors WARNING

### ISSUE THREAD

**Issue by smcnab1** [morosanmihail/HA-LondonTfL#15]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:519
First occurred: 16:05:51 (1 occurrences)
Last logged: 16:05:51

Updating state for sensor.london_tfl_jubilee_940gzzluwhp (<class 'custom_components.london_tfl.sensor.LondonTfLSensor'>) took 0.548 seconds. Please report it to the custom integration author.

Has been okay for a while but since update now getting WARNING in Log relating to speed of state update

**Comment by morosanmihail** [comment]
Should be fine as long as it does get data. It's nothing I can control, as far as I can tell.
