### ISSUE TITLE
HASL Departure card compatability broken?

### ISSUE THREAD

**Issue by PromoFaux** [morosanmihail/HA-LondonTfL#17]
Do you have a copy of the yaml you used to configure the `custom:hasl-departure-card` in the Readme?

I copied the YAML example from their repo and went from there, but nothing appears to be sticking - I am just left with a blank card. 

![image](https://user-images.githubusercontent.com/1998970/210148832-48a3e7c2-f88e-4902-92e2-6380b9ad7656.png)

Data is definitely coming through, as I am able to use the `upcoming-media` card with no issues (I just prefer the look of the HACS one 🙂 )

ETA: Both this integration and the HASL card added through HACS

**Comment by morosanmihail** [comment]
Oooh, good shout. I'll try to remember to update the README as well.

Here ya go:

```
type: custom:hasl-departure-card
header: false
departures: true
deviations: false
timeleft: true
updated: false
name: Departures
adjust_times: false
hide_departed: false
language: en-EN
entities:
  - sensor.london_tfl_dlr_940gzzdlrvc
```

**Comment by PromoFaux** [comment]
Lovely, that's working for me now - thanks!

![image](https://user-images.githubusercontent.com/1998970/210180781-43a54fff-d6ee-4fdf-987e-70652b9d52dc.png)
