### ISSUE TITLE
No data for Southeastern line

### ISSUE THREAD

**Issue by ReX1983** [morosanmihail/HA-LondonTfL#19]
Hey, 

Great extension!

I have tried with the DLR line and it works, but I can't get any data for Southeastern. Tried few stations (e.g. Lewisham) but there is no data for the whole day.

Any idea?

Thanks

**Comment by morosanmihail** [comment]
Thank you! I have a theory (that most non-TfL trains don't actually show up in the TfL API, but they still advertise the lines / stations), but I will try to confirm or deny now.

**Comment by morosanmihail** [comment]
Yep, seems like National Rail does not share all its times with the API yet, and Southeastern is one of them. 
I remember seeing that there's an integration (maybe even baked in) for trains explicitly, so might be worth seeing if that solves that half of the problem!

**Comment by ReX1983** [comment]
What a pity - your integration works so well with DLR!

The official integration limits the queries to once every 5 minutes. It seems pretty limited. How often is the polling in yours?
 
There is another non-official integration (https://github.com/megakid/ha_realtime_trains_api), it is based on https://api.rtt.io/. Which API did you use for yours?

**Comment by morosanmihail** [comment]
I've done some sneakiness to limit polling as well. It gets as much data as possible and only updates when it's close to running out of stuff. Even though the API itself (api.tfl.gov.uk) doesn't seem to be rate limiting, I wanted to have the least amount of footprint possible.

**Comment by ReX1983** [comment]
Is there any chance that Southeastern labels stations differently and we are not getting data because we don't use the right address? Or maybe the line itself is called differently (now that has changed ownership)?

**Comment by morosanmihail** [comment]
Honestly, uncertain. All the lines that show up are the ones their API gives, then all the stations are the ones mapped to the given lines. See `const.py` for the API calls used. 

I probably won't be able to investigate this further. I think it's due to it not being TfL and the stations showing up just as a courtesy. But if you do find an issue in my approach, do give a shout and I'll try to remedy!
