### ISSUE TITLE
Entity naming: Latimer Road displayed as Edgeware Road

### ISSUE THREAD

**Issue by splendstrom** [morosanmihail/HA-LondonTfL#2]
Great intergration - i have been using node-red and mqtt to attempt to do the same thing. Obviously an HA intergration is better!

I've added two lines H&C and Circle Line both with Latimer Road. Although it is the correct ID it displays as Edgeware Road as the default for Circle and Hammersmith for H&C.

Not too much trouble to change it manually but is confusing at first.

Thanks again for the effort!

**Comment by morosanmihail** [comment]
Ah, yes, I should update the description. The name changes to what the destination station is, to be able to, at a glance, see where it goes when used in an Entity card.

**Comment by splendstrom** [comment]
I see. My plan is to create the next train displays within HA and attempt a led matrix display at the top of the front door. That lends itself better to populating all the attributes (i.e. platform name, direction, current stop, etc) with a static name.  

Not sure if that would make it more difficult to create the glance effect.

**Comment by morosanmihail** [comment]
I think doing what you've already done (rename the sensor) should help with achieving the static name, so that should hopefully be fine!

**Comment by morosanmihail** [comment]
Heads up that I've changed attributes slightly to better reflect what other transport components do. Also added `station_name` as an attribute, if you want to use that in any way.
