### ISSUE TITLE
Any plans to extend the component to support bus routes/bus departure times?

### ISSUE THREAD

**Issue by james-fry** [morosanmihail/HA-LondonTfL#20]
Firstly thanks for the great custom component - so easy to install, configure and use with the HASL card.
I used to use the built in [UK transport](https://www.home-assistant.io/integrations/uk_transport/) integration for bus times but since the API hits/day limit was reduced from 1000 to 30 (!) its become useless for departure times (and pretty much anything else either).

Just wondered if you have any plans to extend the component to support buses, or indeed any other the other API capabilities?

I would think Buses would follow the same pattern as tube - select bus route, then select stop.

**Comment by morosanmihail** [comment]
Glad it is helpful!

No current plans to expand what's available, but assuming the TfL API does the same things for buses as it does for trains, then someone could tweak the available lines and see if it works. 

I might try when I have some free time, but that might not be until April :( .

**Comment by morosanmihail** [comment]
Though I think there's a fork that does do buses only, so I might adapt what they did.

**Comment by james-fry** [comment]
Thanks for the reply. I'll keep an eye open in case you add it, and thanks in advance if you do :)

**Comment by james-fry** [comment]
> Though I think there's a fork that does do buses only, so I might adapt what they did.

I've tried out that fork. Looking at the code, to my (rather python deficient) eye it seems a trivial change.
Seems only a couple of sting constant values changed.
The compoents seems to work pretty well, with a small quirks around identifying the correct stop.

- I can install the component via HACS by adding as custom repo - hacs.json has changed name from yours.
- I can add the integration in same way
- I can select the bus route from list (of a great many - who knew so many bus routes in London!)
- The bus stop are then listed but seem to use mostly IDs not human readable names.
- I created a sensor for my local bus line (65) and added random stop. You need to get the ID from TFL website - e.g. https://tfl.gov.uk/bus/stop/490000208A, where 490000208A is the ID for one direction. If you need the other direction it would be (e.g.)  490000208B

**Comment by morosanmihail** [comment]
I've made some changes to this one to add buses as a method of transport, but it seems it doesn't work out of the box.

You can select your chosen method (bus, dlr, tube, etc), then the lines and stations populate nicely. However, for buses, it seems there are no results and it does need a slightly different API call. 

I will likely keep building on top of this as I find time and hopefully have a version that works nicely.

**Comment by morosanmihail** [comment]
I have indeed kept building on top of this a lot earlier than expected. I think I solved it. 

I will create a beta release with the changes. Hopefully it all works ok.

**Comment by morosanmihail** [comment]
Seems fine on my end 5 days in, so I've released it publicly. Do open new issues if you find any!
