### ISSUE TITLE
Cannot reach TfL (National Rail)

### ISSUE THREAD

**Issue by warrenkerrigan** [morosanmihail/HA-LondonTfL#24]
I am having an issue where I don't appear to be able to get any National Rail stations to return a value.

I am getting the error "Cannot reach TfL". I have attempted to get data from South Western Railways, Great Western Railways and the Gatwick Express. All appear to have the same connectivity issue.

Perhaps I am missing an API key or something like that?

You can see it working for busses, but not for National Rail below.

![Screenshot 2024-05-16 at 17 23 37](https://github.com/morosanmihail/HA-LondonTfL/assets/2706208/7adc8836-f5cd-435a-9cbf-b7853fda7e50)
![Screenshot 2024-05-16 at 17 22 51](https://github.com/morosanmihail/HA-LondonTfL/assets/2706208/5804312c-54bc-4b77-9827-415a6467055f)

**Comment by morosanmihail** [comment]
Not sure why it says "Cannot reach TfL", but it is expected that National Rail would not work. It's mostly TfL run services taht show up on their API, with any extra info (such as stations served by National Rail) only showing up as a courtesy, but, afaict, not often populated :( You might have to use a different integration to get train details.

**Comment by warrenkerrigan** [comment]
By the way. Great integration. Keep up the amazing work.

**Comment by morosanmihail** [comment]
I've not tested this, but https://github.com/jfparis/homeassistant_nationalrail seems to fit the bill!
And thank you! But most of the credit goes to TfL for their robust API.
