### ISSUE TITLE
Branch not shown for trains

### ISSUE THREAD

**Issue by marcuscps** [morosanmihail/HA-LondonTfL#25]
I'm monitoring southbound trains from West Finchley station.
There is no information if trains are via Bank or Charring Cross.
Such information is more relevant than the destination itself.

**Comment by morosanmihail** [comment]
You are correct! That would be very useful. I had a couple of minutes just now to confirm if the API has that info, and it does. 

And, to my luck, past me left the code in a nice state that changing what is used is trivial. I'll push a patch imminently.

**Comment by morosanmihail** [comment]
https://github.com/morosanmihail/HA-LondonTfL/releases/tag/v0.4.3 should fix it. If it doesn't, I blame the nasty cold I'm currently nursing.

**Comment by morosanmihail** [comment]
There we go, v0.4.4 should properly fix it. If you see anything wrong, do tell me!

**Comment by marcuscps** [comment]
Amazing!
This was probably the fastest fix ever!
Thanks a lot.

**Comment by morosanmihail** [comment]
No, thank you for raising the issue! Take care!
