### ISSUE TITLE
Buses are broken with recent update

### ISSUE THREAD

**Issue by Artemu** [morosanmihail/HA-LondonTfL#28]
With the recent update in towards/direction the buses all terminate now at a "via" stop rather than their destination. 

![image](https://github.com/morosanmihail/HA-LondonTfL/assets/2136351/788efbd2-ebab-4b8e-b9f2-09f92111d25e)

And it's confirmed that there is no disruptions at present. 

![image](https://github.com/morosanmihail/HA-LondonTfL/assets/2136351/78bf2bf6-5b09-4a3a-8b37-b3ad41693878)

**Comment by morosanmihail** [comment]
Ah, wonderful, TfL being consistent across different types of transport! 
Thank you for raising this, will try to look into it later today.

**Comment by morosanmihail** [comment]
https://github.com/morosanmihail/HA-LondonTfL/releases/tag/v0.4.5 should attempt a fix. Do tell me if it solves it! Local testing shows it's fine, but TfL has a habit of exceptions everywhere.

**Comment by Artemu** [comment]
Can confirm that the data is now showing correctly with the bug fix. Thank you.

**Comment by str3pto** [comment]
Hi, sorry for opening this again, but it seems to be broken again? 
![Screenshot 2024-06-10 231049](https://github.com/morosanmihail/HA-LondonTfL/assets/10393250/9d10c7c7-ef72-4782-8b7a-0b88759421b3)

maybe something else broke?!

**Comment by morosanmihail** [comment]
Looking at the test sensors I have, the one bus one has also broken for me around the same time.

Given the timing, I'm fairly sure this is on TfL API in some way, as the last change to the code was 3 days ago and I have been running it since then, but only broke this morning.

Will investigate, thank you for bringing this up!

**Comment by morosanmihail** [comment]
Yep, seems like most bus stoppoint arrivals are returning empty lists. Will investigate later in the week if it's an API change or just downtime from TfL.

**Comment by morosanmihail** [comment]
But it's definitely a new, unrelated issue. Luckily?

**Comment by str3pto** [comment]
im happy to open as a new issue if you prefer?!

**Comment by morosanmihail** [comment]
My bus is back magically. If yours is still empty, yes please, a new issue would be wonderful!

**Comment by str3pto** [comment]
mine started to work at 1:30 this morning, sorry i didnt check HA before responding here. nice work! keep up :D sorry for the trouble.

**Comment by morosanmihail** [comment]
Haha, thank you, but I didn't do anything this time. I think TfL had a hiccup. For many hours. 
And no trouble at all! Thank you for raising issues when they pop up. Please keep doing that whenever possible!
