### ISSUE TITLE
Filter by platform doesn't work for buses

### ISSUE THREAD

**Issue by mohakkataria** [morosanmihail/HA-LondonTfL#29]
Hi there

First of all thanks for this integration. Have added my fave bus routes to HA and it helps immensely. Been thinking of adding automation to announce TTS closer to my office times the bus arrival times, but while the value of platform for the bus routes is correctly mapped to bus number, the same isn't true for the platform filter. 

Upon looking at the code, I think the issue might be here : https://github.com/morosanmihail/HA-LondonTfL/blob/bc9018d410962320878113d05ec39d1a57e1ad80/custom_components/london_tfl/tfl_data.py#L61 because in case of buses the data says line number, and not platform name.

**Comment by morosanmihail** [comment]
Thanks for finding this and solving it! Legend!

**Comment by AlexTryHarder** [comment]
@mohakkataria Thanks for this commit, very useful.
However im struggling to use this filter. How should I specify filter in YAML file?

```
type: custom:hasl-departure-card
departures: true
deviations: false
timeleft: true
platform: "333"
language: en-EN
entities:
  - sensor.london_tfl_XXXX
```
Tried all variants of "platform:" but nothing seems to work
Thanks!

**Comment by mohakkataria** [comment]
The filter applies when you setup the sensor/integration. Not at the card
level.
