### ISSUE TITLE
Status empty after install

### ISSUE THREAD

**Issue by cstrand89** [morosanmihail/HA-LondonTfL#3]
Hi. I have added two stations on the TfL Tram network but the status for both are just showing "none".

**Comment by morosanmihail** [comment]
I've noticed that with one test TfL station. It's, most of the time, None, until it gets some info for a minute, then it's gone again. I don't know if it's a TfL issue or a component issue, as the other test stations I use properly get next departure (and even several after that) without problems. 

Can you try calling the API directly (`https://api.tfl.gov.uk/line/dlr/arrivals/940GZZDLRVC`, replace `dlr` with `tram` and `940..` with the station ID, which you can get from the sensor name) and see if that reliably gives you results? If it also doesn't, then it's TFL that's wrong.

**Comment by cstrand89** [comment]
Tried with 9400ZZCRWAN as this comes up after selecting Wandle Park in the dropdown as a test and just an empty in return. However, the API seems to return for 940GZZCRWAN. Seems like the dropdown for Wandle Park when setting up has added an extra 0? Is this an error in your code?

**Comment by morosanmihail** [comment]
Thanks for the data! Will look into it now.

**Comment by cstrand89** [comment]
No problem. Any chance you know enough about coding to help get this issue fixed for the main London Tfl component? https://github.com/home-assistant/core/issues/65435 It would be good to be able to pull overall line status.

**Comment by morosanmihail** [comment]
Can't promise much, but I'll take a look when I have more free time.

**Comment by morosanmihail** [comment]
Latest master solves the problem! At least until the API comes up with new surprises.
