### ISSUE TITLE
Warning in logs

### ISSUE THREAD

**Issue by andrey-zotov** [morosanmihail/HA-LondonTfL#32]
Found this in logs, might need fixing:

> 2024-10-30 22:27:44.900 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration london_tfl with title: 490G00013869 and entry_id: 01JBFRNFCY3X6C66N20HXHP1DK, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

![image](https://github.com/user-attachments/assets/0097c96a-74c6-4a65-91b1-ba7bcdaf2959)

**Comment by morosanmihail** [comment]
Ah, yeah. Noticed this a while ago and forgot about it. Will try to tackle when I get some free time, which has not been in abundance recently.

**Comment by morosanmihail** [comment]
Decided to just tackle it now. Was a lot more trivial than I expected. Will get a new version committed, but you can safely ignore the warning for now.
