### ISSUE TITLE
No longer updating

### ISSUE THREAD

**Issue by cvassilas** [morosanmihail/HA-LondonTfL#33]
This error originated from a custom integration.

Logger: custom_components.london_tfl.sensor
Source: custom_components/london_tfl/sensor.py:184
integration: London TfL (documentation, issues)
First occurred: 4 November 2024 at 19:45:05 (39636 occurrences)
Last logged: 07:47:25

There was no reply from TfL servers.

**Comment by morosanmihail** [comment]
Yes, that can happen if either your network connection is down temporarily, or the TfL servers are having issues.
It's a transient issue, so should solve itself after a while.
