### ISSUE TITLE
Time zone issue

### ISSUE THREAD

**Issue by christophe-mailhe** [morosanmihail/HA-LondonTfL#5]
Since the switch to summer time a few weeks ago, the time to station is seems not to calculate properly anymore. 

```
Last refresh 12 April 2022, 23:28:34
Departures
- time_to_station: 1383m 25s platform: Platform 2 line: Platform 2 direction: 0 departure: '2022-04-12T22:32:00Z' destination: Bank DLR Station time: '1383' expected: '2022-04-12T22:32:00Z
```

The time on my HA is set to Europe/London, current TZ=BST. If I switch to view next departure time, rather than time to station, the the time display properly. Issue started the day after we switched to BST. 

Can you have a look when you have a few minutes?

**Comment by christophe-mailhe** [comment]
Yes, sure. Station is DLR / Depford Bridge, which I think is dlr_940gzzdldep,  Platform 2

These are my TZ settings and a fetch of the current attributes from Dev tools > Template

```
UTC Now = {{ utcnow().tzinfo }}
Now TZ info = {{ now().tzinfo }}
Now As TZ info = {{ now().astimezone().tzinfo }}
Now = {{now()}}


{{ state_attr('sensor.london_tfl_dlr_940gzzdldep', 'departures') }}
```

Results:

UTC Now = UTC
Now TZ info = Europe/London
Now As TZ info = BST
Now = 2022-04-13 18:46:00.004656+01:00


[{'time_to_station': '1382m 20s', 'platform': 'Platform 2', 'line': 'Platform 2', 'direction': 0, 'departure': '2022-04-13T17:47:56Z', 'destination': 'Bank DLR Station', 'time': '1382', 'expected': '2022-04-13T17:47:56Z', 'type': 'Metros', 'groupofline': '', 'icon': 'mdi:train'}, {'time_to_station': '1386m 20s', 'platform': 'Platform 2', 'line': 'Platform 2', 'direction': 0, 'departure': '2022-04-13T17:51:56Z', 'destination': 'Bank DLR Station', 'time': '1386', 'expected': '2022-04-13T17:51:56Z', 'type': 'Metros', 'groupofline': '', 'icon': 'mdi:train'}, {'time_to_station': '1390m 20s', 'platform': 'Platform 2', 'line': 'Platform 2', 'direction': 0, 'departure': '2022-04-13T17:55:57Z', 'destination': 'Bank DLR Station', 'time': '1390', 'expected': '2022-04-13T17:55:57Z', 'type': 'Metros', 'groupofline': '', 'icon': 'mdi:train'}]

**Comment by morosanmihail** [comment]
Thank you! I'll sadly not have time to do a deep dive this week, but hopefully next week I should be able to hunt for a reason / great a fix.

**Comment by christophe-mailhe** [comment]
No problem. I have fixed the issue on my local install by changing the datetime().now() used for the calculation to use datetime().utcnow(), and created a pull request.

**Comment by morosanmihail** [comment]
Change doesn't seem to have broken anything, so this seems good to close for now. 
Thank you for catching this and for the PR!
