### ISSUE TITLE
No data pulled for the Northern Line

### ISSUE THREAD

**Issue by betheuil** [morosanmihail/HA-LondonTfL#7]
It appears data is not pulling correctly for some stations on the Northern Line.

For example, 'Euston' pulls properly, but 'Battersea Power Station', 'Nine Elms' or 'Bank' don't.

I sort of understand why Bank doesn't (it currently is closed on the Northern Line) but the other two operate as normal, and they return data sucessfully in the tfl api.

Not sure what the issue is: the entities do not have their names converted automatically, but I can see the NaptanID is correct:

![image](https://user-images.githubusercontent.com/43854404/167442862-7cb55b22-806a-4c68-be96-fa9d85c2571a.png)

**Comment by morosanmihail** [comment]
That seems problematic. I'll try to replicate soon and see what the cause might be.
Thank you for raising!
