### ISSUE TITLE
Add the ability to replace certain words

### ISSUE THREAD

**Issue by dwardu89** [morosanmihail/HA-LondonTfL#8]
I am looking at the Northern line, and some stations are giving the following problems which can be annoying.
![image](https://user-images.githubusercontent.com/3398505/167701239-32baeb03-0f8e-48cf-b057-f7d51ba5cdca.png)

Firstly there is the `Southbound - Platform 4` which could be shortened

Then there is the `Underground Station` part which can be removed

I want to see how to add configuration to allow users to omit certain phrases with blank spaces for the destinations, as well as for the platform.
@morosanmihail I'm new to HASS modifications, however I'm happy to see where I could make the requested changes, if there are more bits that need changes.

**Comment by morosanmihail** [comment]
Ha, I just use whatever the API gives, and it seems to really like being verbose. 
I can't imagine this will be a high priority for me in the foreseeable month or two, but I'm more than happy to review any PRs thrown this way!
